import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  hooks: { afterAllFileWrite: ['prettier --write', 'eslint --fix'] },
  schema: 'dist/apps/friction/autogenerated-schema.gql',
  documents: ['apps/**/*gql.ts', 'libs/**/*gql.ts'],
  generates: {
    'libs/web/data-access-graphql/src/lib/types.ts': {
      plugins: ['typescript'],
    },
    'lib/': {
      preset: 'near-operation-file',
      presetConfig: {
        extension: '.gen.ts',
        baseTypesPath: '~./types',
      },
      plugins: ['typescript-operations', 'typescript-urql'],
      config: {
        webhook: true,
      },
    },
  },
};

export default config;
